/// Stdlib ownership registry — pre-populates `fn_ownership_registry` with ownership metadata
/// for all built-in stdlib functions.
///
/// All stdlib params are annotated `borrow`:
/// - Stdlib functions operate on Atlas values with CoW semantics — they never truly consume.
/// - Registering them prevents `check_call_ownership` from silently skipping stdlib calls.
/// - Future phases can override specific entries with `own`/`share` if needed.
use crate::ast::OwnershipAnnotation;
use std::collections::HashMap;

use super::FnOwnershipEntry;

/// Build `borrow × n` ownership entry.
fn b(n: usize) -> FnOwnershipEntry {
    (vec![Some(OwnershipAnnotation::Borrow); n], None)
}

pub fn build_stdlib_ownership() -> HashMap<String, FnOwnershipEntry> {
    let mut m: HashMap<String, FnOwnershipEntry> = HashMap::with_capacity(512);

    // ── 0-param functions ────────────────────────────────────────────────────
    for name in [
        "channelUnbounded",
        "dateTimeNow",
        "dateTimeUtc",
        "fsGetTempDir",
        "fsTmpdir",
        "fsTmpfile",
        "getCwd",
        "getPid",
        "hashMapNew",
        "hashSetNew",
        "listEnv",
        "None",
        "pathCwd",
        "pathDelimiter",
        "pathExtSeparator",
        "pathHomedir",
        "pathSeparator",
        "pathTempdir",
        "queueNew",
        "random",
        "stackNew",
    ] {
        m.insert(name.to_string(), b(0));
    }

    // ── 1-param functions ────────────────────────────────────────────────────
    for name in [
        "abs",
        "acos",
        "aesGcmGenerateKey",
        "appendFileAsync",
        "arrayIsEmpty",
        "arrayPop",
        "arrayReverse",
        "arrayShift",
        "asin",
        "assert",
        "assertEmpty",
        "assertErr",
        "assertFalse",
        "assertNone",
        "assertNoThrow",
        "assertOk",
        "assertSome",
        "assertThrows",
        "asyncMutex",
        "asyncMutexGet",
        "atan",
        "atomicLoad",
        "atomicNew",
        "await",
        "cryptoNsBlake3",
        "encodingNsBase64Decode",
        "encodingNsBase64Encode",
        "encodingNsBase64UrlDecode",
        "encodingNsBase64UrlEncode",
        "ceil",
        "channelBounded",
        "channelIsClosed",
        "channelReceive",
        "channelSelect",
        "cos",
        "createDir",
        "dateTimeDay",
        "dateTimeDayOfYear",
        "dateTimeFromComponents",
        "dateTimeFromTimestamp",
        "dateTimeGetOffset",
        "dateTimeGetTimezone",
        "dateTimeHour",
        "dateTimeMinute",
        "dateTimeMonth",
        "dateTimeParseIso",
        "dateTimeParseRfc2822",
        "dateTimeParseRfc3339",
        "dateTimeSecond",
        "dateTimeToIso",
        "dateTimeToLocal",
        "dateTimeToRfc2822",
        "dateTimeToRfc3339",
        "dateTimeToTimestamp",
        "dateTimeToUtc",
        "dateTimeWeekday",
        "dateTimeYear",
        "durationFormat",
        "durationFromDays",
        "durationFromHours",
        "durationFromMinutes",
        "durationFromSeconds",
        "Err",
        "exec",
        "fileExists",
        "fileInfo",
        "flatten",
        "floor",
        "fsAtime",
        "fsCtime",
        "fsInode",
        "fsIsDir",
        "fsIsFile",
        "fsIsSymlink",
        "fsMkdir",
        "fsMkdirp",
        "fsMtime",
        "fsPermissions",
        "fsReaddir",
        "fsReadlink",
        "fsResolveSymlink",
        "fsRmdir",
        "fsRmdirRecursive",
        "fsSize",
        "fsSortEntries",
        "fsTmpfileNamed",
        "fsWalk",
        "fsWatch",
        "fsWatchNext",
        "futureAll",
        "futureIsPending",
        "futureIsRejected",
        "futureIsResolved",
        "futureNew",
        "futureRace",
        "futureReject",
        "futureResolve",
        "getEnv",
        "gzipDecompress",
        "gzipDecompressString",
        "gzipIsGzip",
        "hashMapClear",
        "hashMapCopy",
        "hashMapEntries",
        "hashMapFromEntries",
        "hashMapIsEmpty",
        "hashMapKeys",
        "hashMapSize",
        "hashMapValues",
        "hashSetClear",
        "hashSetFromArray",
        "hashSetIsEmpty",
        "hashSetSize",
        "hashSetToArray",
        "encodingNsHexDecode",
        "encodingNsHexEncode",
        "httpBody",
        "httpContentLength",
        "httpContentType",
        "httpDelete",
        "httpDeleteAsync",
        "httpGet",
        "httpGetAsync",
        "httpHeaders",
        "httpIsClientError",
        "httpIsRedirect",
        "httpIsServerError",
        "httpIsSuccess",
        "httpParseJson",
        "httpPatch",
        "httpPost",
        "httpPostAsync",
        "httpPostJson",
        "httpPut",
        "httpPutAsync",
        "httpRequest",
        "httpRequestDelete",
        "httpRequestGet",
        "httpRequestPatch",
        "httpRequestPost",
        "httpRequestPut",
        "httpSend",
        "httpSendAsync",
        "httpStatus",
        "httpStatusText",
        "httpUrl",
        "interval",
        "is_err",
        "is_none",
        "is_ok",
        "is_some",
        "isArray",
        "isBool",
        "isErr",
        "isFunction",
        "isNone",
        "isNull",
        "isNumber",
        "isObject",
        "isOk",
        "isSome",
        "isString",
        // isValidJSON removed B23
        "joinAll",
        "jsonAsBool",
        "jsonAsNumber",
        "jsonAsString",
        // jsonIsNull removed B23 (was bare global; still exists as JsonValue instance method)
        "len",
        "log",
        // minifyJSON removed B23
        "Ok",
        "parseFloat",
        // parseJSON removed B23
        "pathAbsolute",
        "pathBasename",
        "pathCanonical",
        "pathDirname",
        "pathDrive",
        "pathExists",
        "pathExtension",
        "pathIsAbsolute",
        "pathIsRelative",
        "pathJoinArray",
        "pathNormalize",
        "pathParent",
        "pathParse",
        "pathToPlatform",
        "pathToPosix",
        "pathToWindows",
        "pop",
        "print",
        "processNsIsRunning",
        "processNsKill",
        "processNsOutput",
        "processNsSpawn",
        "processNsStderr",
        "processNsStdin",
        "processNsStdout",
        "processNsWaitFor",
        "queueClear",
        "queueDequeue",
        "queueIsEmpty",
        "queuePeek",
        "queueSize",
        "queueToArray",
        "readDir",
        "readFile",
        "readFileAsync",
        "reflect_clone",
        "reflect_get_function_arity",
        "reflect_get_function_name",
        "reflect_get_length",
        "reflect_is_callable",
        "reflect_is_empty",
        "reflect_is_primitive",
        "reflect_typeof",
        "reflect_type_describe",
        "reflect_value_to_string",
        "regexEscape",
        "regexNew",
        "removeDir",
        "removeFile",
        "result_err",
        "result_ok",
        "reverse",
        "round",
        "rwLockNew",
        "rwLockRead",
        "rwLockTryRead",
        "rwLockTryWrite",
        "semaphoreAcquire",
        "semaphoreAvailable",
        "semaphoreNew",
        "semaphoreRelease",
        "semaphoreTryAcquire",
        "sha256",
        "sha512",
        "shell",
        "shift",
        "sign",
        "sin",
        "sleep",
        "Some",
        "spawn",
        "sqrt",
        "stackClear",
        "stackIsEmpty",
        "stackPeek",
        "stackPop",
        "stackSize",
        "stackToArray",
        "str",
        "tan",
        "tarList",
        "taskCancel",
        "taskId",
        "taskJoin",
        "taskName",
        "taskStatus",
        "tcpAccept",
        "tcpClose",
        "tcpConnect",
        "tcpListen",
        "tcpListenerAddr",
        "tcpListenerClose",
        "tcpLocalAddr",
        "tcpRead",
        "tcpRemoteAddr",
        "timer",
        "tlsClose",
        "tlsConnect",
        "tlsRead",
        "toBool",
        // toJSON removed B23
        "toLowerCase",
        "toNumber",
        "toString",
        "toUpperCase",
        "trim",
        "trimEnd",
        "trimStart",
        "type_of",
        "typeof",
        "udpBind",
        "udpClose",
        "udpLocalAddr",
        "udpReceive",
        "unsetEnv",
        "unwrap",
        "encodingNsUrlDecode",
        "encodingNsUrlEncode",
        "value_to_string",
        "wsClose",
        "wsConnect",
        "wsPing",
        "wsReceive",
        "zipComment",
        "zipCompressionRatio",
        "zipList",
        "zipValidate",
    ] {
        m.insert(name.to_string(), b(1));
    }

    // ── 2-param functions ────────────────────────────────────────────────────
    for name in [
        "aesGcmDecrypt",
        "aesGcmEncrypt",
        "appendFile",
        "arrayIncludes",
        "arrayIndexOf",
        "arrayLastIndexOf",
        "arrayPush",
        "arrayUnshift",
        "assertContains",
        "assertEqual",
        "assertLength",
        "assertNotEqual",
        "asyncMutexSet",
        "atomicAdd",
        "atomicStore",
        "atomicSub",
        "channelSend",
        "charAt",
        "concat",
        "dateTimeAddDays",
        "dateTimeAddHours",
        "dateTimeAddMinutes",
        "dateTimeAddSeconds",
        "dateTimeCompare",
        "dateTimeDiff",
        "dateTimeFormat",
        "dateTimeInTimezone",
        "dateTimeParse",
        "dateTimeToCustom",
        "dateTimeToTimezone",
        "dateTimeTryParse",
        "endsWith",
        "expect",
        "fsFilterEntries",
        "fsSymlink",
        "futureCatch",
        "futureThen",
        "gzipCompressionRatio",
        "hasField",
        "hashMapGet",
        "hashMapHas",
        "hashMapRemove",
        "hashSetAdd",
        "hashSetDifference",
        "hashSetHas",
        "hashSetIntersection",
        "hashSetIsSubset",
        "hashSetIsSuperset",
        "hashSetRemove",
        "hashSetSymmetricDifference",
        "hashSetUnion",
        "hasMethod",
        "hasTag",
        "httpCheckPermission",
        "httpGetJson",
        "httpHeader",
        "httpSetAuth",
        "httpSetBody",
        "httpSetFollowRedirects",
        "httpSetMaxRedirects",
        "httpSetQuery",
        "httpSetTimeout",
        "httpSetUserAgent",
        "includes",
        "indexOf",
        "isType",
        "join",
        // jsonGetArray/Bool/Number/Object/String removed B23 (bare globals; kept as JsonValue instance methods)
        "lastIndexOf",
        "max",
        "min",
        "pathEquals",
        "pathJoin",
        "pathRelative",
        "parseInt",
        "pow",
        // prettifyJSON removed B23
        "queueEnqueue",
        "reflect_deep_equals",
        "reflect_same_type",
        "regexCaptures",
        "regexCapturesNamed",
        "regexFind",
        "regexFindAll",
        "regexIsMatch",
        "regexMatchIndices",
        "regexNewWithFlags",
        "regexSplit",
        "regexTest",
        "repeat",
        "rwLockWrite",
        "setEnv",
        "split",
        "stackPush",
        "startsWith",
        "tarContains",
        "tarExtract",
        "tarExtractGz",
        "tcpReadBytes",
        "tcpSetNodelay",
        "tcpSetTimeout",
        "tcpWrite",
        "timeout",
        "tlsWrite",
        "udpSend",
        "udpSetTimeout",
        "unshift",
        "unwrap_or",
        "unwrapOr",
        "writeFile",
        "writeFileAsync",
        "wsSend",
        "wsSendBinary",
        "zipContains",
        "zipExtract",
    ] {
        m.insert(name.to_string(), b(2));
    }

    // ── 3-param functions ────────────────────────────────────────────────────
    for name in [
        "atomicCompareExchange",
        "clamp",
        "hashMapPut",
        "cryptoNsHmac",
        "httpSetHeader",
        "padEnd",
        "padStart",
        "regexReplace",
        "regexReplaceAll",
        "regexSplitN",
        "replace",
        "replaceAll",
        "slice",
        "substring",
        "tarCreate",
        "zipExtractFiles",
    ] {
        m.insert(name.to_string(), b(3));
    }

    // ── Variadic functions (register minimum fixed-param arity) ──────────────
    // gzipCompress(data, level?) — 1 required
    m.insert("gzipCompress".to_string(), b(1));
    // tarCreateGz(output, sources...) — 2 required
    m.insert("tarCreateGz".to_string(), b(2));
    // zipAddFile(zip, path, name?) — 2 required
    m.insert("zipAddFile".to_string(), b(2));
    // zipCreate(output, files...) — 1 required
    m.insert("zipCreate".to_string(), b(1));
    // zipCreateWithComment(output, comment, files...) — 2 required
    m.insert("zipCreateWithComment".to_string(), b(2));
    // arraySort(arr, compareFn?) — 1 required
    m.insert("arraySort".to_string(), b(1));
    // crypto.hmacVerify(key, data, sig, algo) — 4 required
    m.insert("cryptoNsHmacVerify".to_string(), b(4));

    m
}
